[workspace]
members = ["projects/*"]
default-members = [
     "projects/ycc",
#    "projects/ygg-bootstrap",
#    "projects/ygg-core",
#    "projects/ygg-shared",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"