[package]
name = "yggdrasil-core"
description = "Yggdrasil grammar for the tree-sitter parsing library"
version = "0.1.1"
authors = ["Aster <192608617@qq.com>"]
license = "MPL2.0"
readme = "../../readme.md"
keywords = ["incremental", "parsing", "rust"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/ygg-lang/yggdrasil-rs"
edition = "2021"

include = [
    "src/*",
]

[dependencies]
yggdrasil-bootstrap = { version = "0.1", path = "../ygg-bootstrap" }
tokio = { version = "1.14.0", features = ["io-std", "rt-multi-thread", "macros", "test-util"] }
serde_json = "1.0.72"
indexmap = "1.7.0"
convert_case = "0.4.0"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
rkyv = "0.7.25"
toml = "0.5.8"
dashmap = "4.0.2"
thiserror = "1.0.30"
anyhow = "1.0.51"
ariadne = "0.1.3"
itertools = "0.10.3"
# same as tower-lsp = "0.14"
lsp-types = { version = "0.91.1", features = ["proposed"], optional = true }
railroad = { version = "0.1.1", optional = true }
lrpeg = {version = "0.4", git = "https://github.com/ygg-lang/lrpeg", optional = true}

[features]
default = ["lsp", "lrpeg", "railroad"]
lsp = ["lsp-types"]

[dev-dependencies]


[build-dependencies]
